// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4zies8d-RztyvWnxlZfUf3FBHmFDaFtw',
    appId: '1:998057767723:web:0c8ee93879f4520ff20b6e',
    messagingSenderId: '998057767723',
    projectId: 'bms-report-mvp',
    authDomain: 'bms-report-mvp.firebaseapp.com',
    storageBucket: 'bms-report-mvp.firebasestorage.app',
    measurementId: 'G-RN3R7LSLQD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEJVJCSxAILHR3E32ZyhvgngyrsO3ugag',
    appId: '1:998057767723:android:51ca53889c1a9905f20b6e',
    messagingSenderId: '998057767723',
    projectId: 'bms-report-mvp',
    storageBucket: 'bms-report-mvp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsmhSGhk1hCYvz_zI9h4Ev1YsMgLGu_PQ',
    appId: '1:998057767723:ios:407ded44212c7a14f20b6e',
    messagingSenderId: '998057767723',
    projectId: 'bms-report-mvp',
    storageBucket: 'bms-report-mvp.firebasestorage.app',
    iosBundleId: 'edu.bmsce.bmsreport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsmhSGhk1hCYvz_zI9h4Ev1YsMgLGu_PQ',
    appId: '1:998057767723:ios:407ded44212c7a14f20b6e',
    messagingSenderId: '998057767723',
    projectId: 'bms-report-mvp',
    storageBucket: 'bms-report-mvp.firebasestorage.app',
    iosBundleId: 'edu.bmsce.bmsreport',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4zies8d-RztyvWnxlZfUf3FBHmFDaFtw',
    appId: '1:998057767723:web:00be4fb085637d7ff20b6e',
    messagingSenderId: '998057767723',
    projectId: 'bms-report-mvp',
    authDomain: 'bms-report-mvp.firebaseapp.com',
    storageBucket: 'bms-report-mvp.firebasestorage.app',
    measurementId: 'G-ZHDNYZ21D9',
  );
}
